---
title: Clustering and differential expression analysis of PBMC3 using COTAN
---


```{r, output=FALSE, warning=FALSE}
library(COTAN)
library(Seurat)
library(tibble)
library(ggplot2)
library(zeallot)
options(parallelly.fork.enable = TRUE)
source("../../libraries/utils.R")

dataset_name = 'PBMC3'
DATASET_PATH = "../../dataset/"
inDataDir = paste(DATASET_PATH, dataset_name, '-Filtered/', sep='')
outDir = paste("../../results/", dataset_name, '/COTAN/', sep='')
if (!dir.exists(outDir)) {
  dir.create(outDir, recursive = TRUE, showWarnings = FALSE)
}

setLoggingLevel(2)
setLoggingFile(file.path(outDir, paste(dataset_name, "_analysis.log", sep='')))
```

Data loading

```{r, echo=TRUE, eval=FALSE}
PBMC3 <- readRDS(file = file.path(inDataDir, paste0(dataset_name, ".cotan.RDS")))
```

```{r, echo=FALSE, EVAL=TRUE}
PBMC3 <- readRDS(file = file.path(outDir, paste0(dataset_name, ".cotan.RDS")))
```

Calculate genes’ COEX

```{r, echo=TRUE, eval=FALSE}
PBMC3 <- proceedToCoex(
  PBMC3,
  calcCoex = TRUE,
  cores = 10,
  saveObj = TRUE,
  outDir = outDir
)
```

```{r, echo=TRUE, eval=TRUE}
gdiData <- calculateGDI(PBMC3)
genesToLabel <- head(
  rownames(gdiData[order(gdiData[["GDI"]], decreasing = TRUE), ]),
  n = 50L
)
sort(genesToLabel)
```

```{r, echo=TRUE, eval=TRUE}
gdiData[genesToLabel[[50L]], "GDI"]
```

```{r, echo=TRUE, eval=TRUE}
gdiPlot <- GDIPlot(
  PBMC3,
  GDIIn = gdiData,
  GDIThreshold = 1.4,
  genes = list("Top 10 GDI genes" = genesToLabel[1L:10L])
)
plot(gdiPlot)
```

Clustering

```{r, echo=TRUE, eval=FALSE}
c(splitClusters, splitCoexDF) %<-%
  cellsUniformClustering(
    PBMC3,
    GDIThreshold = 1.4,
    cores = 13,
    saveObj = TRUE,
    outDir = outDir
  )

PBMC3 <- addClusterization(
  PBMC3,
  clName = "split",
  clusters = splitClusters,
  coexDF = splitCoexDF,
  override = TRUE
)
```

```{r, echo=TRUE, eval=TRUE}
splitClusters <- getClusterizationData(PBMC3, clName = "split")[[1]]
table(splitClusters)
```

Merge uniform clusters

```{r, echo=TRUE, eval=FALSE}
c(mergedClusters, mergedCoexDF) %<-%
  mergeUniformCellsClusters(PBMC3, clusters = splitClusters,
                            GDIThreshold = 1.4, cores = 13,
                            saveObj = TRUE, outDir = outDir)

PBMC3 <- addClusterization(PBMC3, clName = "merged",
                             clusters = mergedClusters,
                             coexDF = mergedCoexDF,
                             override = TRUE)
```

```{r, echo=TRUE, eval=TRUE}
mergedClusters <- getClusterizationData(PBMC3, clName = "merged")[[1]]
table(mergedClusters)
```

Save the clustering result

```{r, echo=TRUE, eval=FALSE}
final_clusters = mergedClusters
final_clusters_name = "merged"
cluster = as.data.frame(final_clusters)
colnames(cluster)[colnames(cluster) == deparse(substitute(final_clusters))] <- "cluster"
cluster$cluster = match(cluster$cluster, levels(final_clusters))
cluster$cell = rownames(cluster)
rownames(cluster) = c(1:nrow(cluster))
write_clustering(outDir, cluster, "cell", "cluster")
```

Differential expression

```{r, echo=TRUE, eval=FALSE}
coexDF <- DEAOnClusters(PBMC3, clusters = final_clusters)
PBMC3 <- addClusterizationCoex(PBMC3, clName = final_clusters_name,
                             coexDF = coexDF)
```

```{r, echo=TRUE, eval=FALSE}
saveRDS(PBMC3, file = file.path(outDir, paste0(dataset_name, ".cotan.RDS")))
```

Save markers

```{r, echo=TRUE, eval=FALSE}
write_markers = function(ourDir, clusters, coex, TOP_MARKER_NUM, decreasing) {
    markers = data.frame()

    for (cluster_id in (levels(clusters))) {
        cluster_markers = data.frame()
        pv = coex[, cluster_id]
        names(pv) = rownames(coex)
        sorted_pv = sort(pv, decreasing = decreasing)
        cluster_markers = data.frame(gene = names(sorted_pv)[1:TOP_MARKER_NUM],
                                    cluster = match(cluster_id, levels(clusters)),
                                    rank = 1:TOP_MARKER_NUM)

        markers = rbind(markers, cluster_markers)
    }
    colnames(markers) = c("gene","cluster","rank")

    write.csv(markers, "markers.csv", row.names = FALSE)
}

TOP_MARKER_NUM = 500

numCells <- getNumCells(PBMC3)
pvals <- pValueFromDEA(coexDF, numCells)

write_markers(outDir, final_clusters, pvals, TOP_MARKER_NUM, FALSE)
```

```{r, echo=TRUE, eval=TRUE}
sessionInfo()
```