---
title: Clustering and differential expression analysis of PBMC4 using Seurat
---

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(DropletUtils)
source("../../libraries/utils.R")
```

Data loading and preparation

```{r}
dataset_name = "PBMC4"
dataset_path = '../../dataset/'

DATA_DIR = paste(dataset_path, dataset_name, '-Filtered/10X', sep='')
LABEL_PATH = paste(dataset_path, dataset_name, '-Filtered/celltypist_labels.csv', sep='')
OUT_RES_DIR = paste("../../results/", dataset_name, "/seurat", sep='')
dir.create(OUT_RES_DIR, recursive = TRUE, showWarnings = FALSE)

TOP_MARKER_NUM = 500
```

Dataset loading

```{r}
pbmc.data <- Read10X(DATA_DIR, strip.suffix=TRUE)
pbmc <- CreateSeuratObject(counts = pbmc.data, min.cells = 0, min.features = 0)
```

Studying feature variance

```{r}
plot(log(sort(apply(pbmc.data,1,var), decreasing=TRUE)))
```

Data normalization

```{r}
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
```

Feature selection

```{r}
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000) # nfeatures chosen based on elbow plot above
VariableFeaturePlot(pbmc)
```

Feature scaling

```{r}
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
```

Clustering

Plot pca explained variance ratio to choose number of components

```{r}
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
ElbowPlot(object = pbmc, ndims = 50)
```

Perform the clustering

```{r}
pbmc <- FindNeighbors(pbmc, dims = 1:16) # chosen based on elbow plot above
pbmc <- FindClusters(pbmc)
```

Save the clustering results

```{r}
label_df = data.frame(Idents(pbmc))
label_df$cell <- rownames(label_df)
rownames(label_df) <- 1:nrow(label_df)
colnames(label_df)[colnames(label_df) == "Idents.pbmc."] <- "computed_id"
label_df$computed_id <- as.numeric(label_df$computed_id)
write_clustering(OUT_RES_DIR, label_df, "cell", "computed_id")
```

Differential expression

```{r}
pbmc.markers <- FindAllMarkers(pbmc)
```

Save markers

```{r}
pbmc.markers$cluster <- as.numeric(pbmc.markers$cluster)
write_markers(OUT_RES_DIR, pbmc.markers, "gene", "cluster", "p_val_adj", FALSE, TOP_MARKER_NUM)
```

```{r}
sessionInfo()
```