```{r}
library(ggplot2)
library(tibble)
library(zeallot)
library(COTAN)
library(DropletUtils)

options(parallelly.fork.enable = TRUE)

DATASETS_FOLDER = './dataset/'
NAME = 'peripheral-blood'

inDataDir  = paste(DATASETS_FOLDER, NAME, sep='')
outDataDir = paste(DATASETS_FOLDER, NAME, '-filtered/', sep='')
out_10x_dir = paste(outDataDir, '10x/', sep='')
dir.create(outDataDir, recursive = TRUE, showWarnings = FALSE)

setLoggingLevel(2)
setLoggingFile(file.path(outDataDir, "PBMC_analysis.log"))

library(Seurat)
allData <- Read10X(data.dir = inDataDir, strip.suffix = TRUE)
data = allData[[1]]

sampleCondition <- "PBMC" # TODO: ??
PBMC <- COTAN(raw = data)
PBMC <- initializeMetaDataset(
  PBMC,
  GEO = "10X PBMC",
  sequencingMethod = "10X",
  sampleCondition = sampleCondition
)
```

```{r}
cellSizePlot(PBMC, splitPattern = "-", numCol = 2)
```

```{r}
cellsSizeThr <- 30000
PBMC <- addElementToMetaDataset(
  PBMC,
  "Cells size threshold",
  cellsSizeThr
)
cells_to_rem <- getCells(PBMC)[getCellsSize(PBMC) > cellsSizeThr]
PBMC <- dropGenesCells(PBMC, cells = cells_to_rem)
cellSizePlot(PBMC, splitPattern = "-", numCol = 2)
```

```{r}
genesSizePlot(PBMC, splitPattern = "-", numCol = 2)
```

```{r}
genesSizeThr <- 4000
PBMC <- addElementToMetaDataset(PBMC, "Num genes threshold", genesSizeThr)
numExprGenes <- getNumExpressedGenes(PBMC)
cells_to_rem <- names(numExprGenes)[numExprGenes > genesSizeThr]
PBMC <- dropGenesCells(PBMC, cells = cells_to_rem)
genesSizePlot(PBMC, splitPattern = "-", numCol = 2)
```

```{r}
mitGenesPattern <- "^[Mm][Tt]-"
getGenes(PBMC)[grep(mitGenesPattern, getGenes(PBMC))]
```

```{r}
c(mitPlot, mitSizes) %<-%
  mitochondrialPercentagePlot(
  PBMC,
  genePrefix = mitGenesPattern,
  splitPattern = "-",
  numCol = 2
)
plot(mitPlot)
```

```{r}
mitPercThr <- 10
PBMC <- addElementToMetaDataset(
  PBMC,
  "Mitoc. perc. threshold",
  mitPercThr
)
cells_to_rem <- rownames(mitSizes)[mitSizes[["mit.percentage"]] > mitPercThr]
PBMC <- dropGenesCells(PBMC, cells = cells_to_rem)
c(mitPlot, mitSizes) %<-%
  mitochondrialPercentagePlot(
    PBMC,
    genePrefix = mitGenesPattern,
    splitPattern = "-",
    numCol = 2)
plot(mitPlot)
```

```{r}
ribGenesPattern <- "^RP[SL]\\d+"
getGenes(PBMC)[grep(ribGenesPattern, getGenes(PBMC))]
```

```{r}
c(ribPlot, ribSizes) %<-%
  mitochondrialPercentagePlot(
    PBMC,
    genePrefix = mitGenesPattern,
    splitPattern = "-", numCol = 2)
plot(ribPlot)
```

```{r}
cellSizePlot(PBMC, splitPattern = "-", numCol = 2)
```

```{r}
genesSizePlot(PBMC, splitPattern = "-", numCol = 2)
```

```{r}
PBMC <- clean(PBMC)
c(pcaCellsPlot, pcaCellsData, genesPlot, UDEPlot, nuPlot, zoomedNuPlot) %<-% cleanPlots(PBMC)
plot(pcaCellsPlot)
```


```{r}
plot(genesPlot)
```

```{r}
PBMC <- addElementToMetaDataset(PBMC, "Num drop B group", 0)
```

```{r}
plot(UDEPlot)
```

```{r}
plot(nuPlot)
```

```{r}
plot(zoomedNuPlot)
```

```{r}
nuDf <- data.frame("nu" = sort(getNu(PBMC)), "n" = seq_along(getNu(PBMC)))
yset <- 0.16 # the threshold to remove low UDE cells
PBMC <- addElementToMetaDataset(PBMC, "Threshold low UDE cells:", yset)

cells_to_rem <- rownames(nuDf)[nuDf[["nu"]] < yset]
PBMC <- dropGenesCells(PBMC, cells = cells_to_rem)
PBMC <- clean(PBMC)
```

```{r}
c(pcaCellsPlot, pcaCellsData, genesPlot, UDEPlot, nuPlot, zoomedNuPlot) %<-% cleanPlots(PBMC)
plot(pcaCellsPlot)
```

```{r}
write10xCounts(out_10x_dir, getRawData(PBMC))
```
